# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  adminAddr: 0.0.0.0:15000
  database:
    url: sqlite:///data/data.db
  modelCatalog:
  - file: /base-costs.json
gateways:
  llm:
    port: 4000
  ui:
    port: 8081
llm:
  gateways:
  - llm
  policies:
    cors:
      allowOrigins:
      - '*'
      - http://localhost:15000
      allowHeaders:
      - '*'
      allowMethods:
      - GET
      - POST
      - OPTIONS
  models:
  - name: openai/gpt-4.1
    provider: openAI
    params:
      model: gpt-4.1
      apiKey: $OPENAI_API_KEY
  - name: openai/*
    provider: openAI
    params:
      model: gpt-4.1-nano
      apiKey: $OPENAI_API_KEY
frontendPolicies:
  http:
    maxBufferSize: 33554432
mcp:
  port: 3000
  targets: []
