#!/usr/bin/env bash
#
# setup.sh — one command to stand up the AgentGateway cost & tokenomics
# dashboard demo locally, in Docker, pre-populated with mock fleet traffic.
#
# What it does:
#   1. Preflight (docker, OPENAI_API_KEY, a Python runner, curl)
#   2. Fetch the mock-log generator (gen-mock-logs.py)
#   3. Generate a SQLite DB with the SAME schema the gateway logs to
#   4. Write config.yaml (database + cost catalog + live OpenAI route)
#   5. Run agentgateway in Docker, mounting the config, catalog, and DB
#
# Usage:
#   export OPENAI_API_KEY='sk-...'
#   ./setup.sh
#
# Teardown:
#   docker rm -f agw-cost-demo
set -euo pipefail

# ----------------------------------------------------------------------------
# Config (override via env)
# ----------------------------------------------------------------------------
VERSION="${VERSION:-v1.3.1}"
IMAGE="cr.agentgateway.dev/agentgateway:${VERSION}"
CONTAINER="agw-cost-demo"
VOLUME="agw-cost-demo-data"          # SQLite lives here (see note below)
GEN_URL="https://raw.githubusercontent.com/sebbycorp/Instruqt-demos/main/01-ai-cost-webinar-workshop/assets/gen-mock-logs.py"

# Mock-data shape (override via env)
REQUESTS="${REQUESTS:-5000}"
DAYS="${DAYS:-7}"

# Resolve to this script's directory so it works from anywhere.
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
die() { printf '\033[1;31mError:\033[0m %s\n' "$*" >&2; exit 1; }

# ----------------------------------------------------------------------------
# 1. Preflight
# ----------------------------------------------------------------------------
say "Preflight checks"
command -v docker >/dev/null 2>&1 || die "docker is not installed or not on PATH."
docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker and retry."
command -v curl   >/dev/null 2>&1 || die "curl is required."
[ -n "${OPENAI_API_KEY:-}" ] || die "OPENAI_API_KEY is not set. Run: export OPENAI_API_KEY='sk-...'"
[ -f base-costs.json ] || die "base-costs.json not found in $DIR (the model cost catalog)."

# Pick a Python runner for the generator (uv preferred, python3 >=3.11 fallback).
if command -v uv >/dev/null 2>&1; then
  GEN_RUN=(uv run)
elif command -v python3 >/dev/null 2>&1; then
  PYVER="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
  PYOK="$(python3 -c 'import sys; print(1 if sys.version_info[:2] >= (3,11) else 0)')"
  [ "$PYOK" = "1" ] || die "python3 $PYVER found, but the generator needs >=3.11 (or install uv: https://astral.sh/uv)."
  GEN_RUN=(python3)
else
  die "Need 'uv' or 'python3 >=3.11' to run the mock-log generator. Install uv: https://astral.sh/uv"
fi

# ----------------------------------------------------------------------------
# 2. Fetch the mock-log generator
# ----------------------------------------------------------------------------
if [ -f gen-mock-logs.py ]; then
  say "Using existing gen-mock-logs.py"
else
  say "Fetching gen-mock-logs.py"
  curl -fsSL "$GEN_URL" -o gen-mock-logs.py || die "Failed to download generator from $GEN_URL"
fi

# ----------------------------------------------------------------------------
# 3. Generate mock data (same schema the gateway logs to)
# ----------------------------------------------------------------------------
say "Generating mock fleet traffic -> data/data.db (${REQUESTS} requests, ${DAYS} days)"
mkdir -p data
"${GEN_RUN[@]}" gen-mock-logs.py --replace --requests "$REQUESTS" --days "$DAYS" -o data/data.db

# ----------------------------------------------------------------------------
# 4. Write config.yaml
# ----------------------------------------------------------------------------
say "Writing config.yaml"
cat > config.yaml <<'YAML'
# yaml-language-server: $schema=https://agentgateway.dev/schema/config
#
# Cost & tokenomics dashboard demo config (generated by setup.sh).
# The admin UI Costs/Analytics pages read config.database; the mock generator
# writes the same request_logs schema, so the dashboard is pre-populated.
config:
  adminAddr: "0.0.0.0:15000"        # admin UI + dashboards (reachable from host)
  database:
    url: "sqlite:///data/data.db"   # /data is the mounted ./data dir in the container
  modelCatalog:
    - file: /base-costs.json        # per-model rates so every request is priced

llm:
  port: 4000
  policies:
    cors:
      allowOrigins: ["*"]
      allowHeaders: ["*"]
      allowMethods: ["GET", "POST", "OPTIONS"]
  models:
    - name: "openai/gpt-4.1"
      provider: openAI
      params:
        model: gpt-4.1
        apiKey: "$OPENAI_API_KEY"
    - name: "openai/*"              # fallback: cheaper nano model
      provider: openAI
      params:
        model: gpt-4.1-nano
        apiKey: "$OPENAI_API_KEY"

frontendPolicies:
  http:
    maxBufferSize: 33554432
YAML

# ----------------------------------------------------------------------------
# 5. Run agentgateway in Docker
#
# The request_logs DB lives in a named volume, NOT a host bind mount: on Docker
# Desktop for macOS, SQLite write locking / WAL fail over the bind-mount FS
# ("disk I/O error", code 522), so the gateway could read seeded mock data but
# never append live calls. A named volume lives in the Linux VM's real FS, where
# SQLite works. We seed it with the generated DB before starting the gateway.
# ----------------------------------------------------------------------------
say "Pulling ${IMAGE}"
docker pull "$IMAGE" >/dev/null

say "Removing any previous '${CONTAINER}' container and data volume"
docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
docker volume rm "$VOLUME" >/dev/null 2>&1 || true

say "Seeding mock data into volume '${VOLUME}'"
docker volume create "$VOLUME" >/dev/null
SEED_CID="$(docker create -v "$VOLUME:/data" "$IMAGE")"
docker cp "$DIR/data/data.db" "$SEED_CID:/data/data.db"
docker rm "$SEED_CID" >/dev/null

say "Starting agentgateway"
# --user 0:0: the image runs as UID 65532 (distroless nonroot), but the seeded
# DB and volume dir are root-owned, so the gateway needs root to create the
# SQLite WAL/journal files and append live request logs.
docker run -d --name "$CONTAINER" \
  --user 0:0 \
  -p 4000:4000 -p 15000:15000 \
  -e OPENAI_API_KEY \
  -v "$DIR/config.yaml:/config.yaml" \
  -v "$DIR/base-costs.json:/base-costs.json" \
  -v "$VOLUME:/data" \
  "$IMAGE" -f /config.yaml >/dev/null

# Give it a moment, then verify it's still up.
sleep 4
if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
  echo "----- container logs -----"
  docker logs "$CONTAINER" 2>&1 | tail -30
  die "Container '${CONTAINER}' exited. See logs above."
fi

cat <<EOF

$(say "Ready 🚀")

  Dashboard (Costs / Analytics):  http://localhost:15000/ui/
  LLM endpoint:                   http://localhost:4000

  The dashboard is pre-loaded with ${REQUESTS} mock requests across ${DAYS} days.

  Make a real call (also logged to the dashboard):

    curl -s http://localhost:4000/v1/chat/completions \\
      -H 'Content-Type: application/json' \\
      -d '{"model":"openai/gpt-4.1","messages":[{"role":"user","content":"Say hi in 3 words."}],"max_tokens":20}'

  Inspect the live DB:
    docker cp ${CONTAINER}:/data/data.db /tmp/live.db && sqlite3 /tmp/live.db 'SELECT COUNT(*) FROM request_logs;'

  Logs:      docker logs -f ${CONTAINER}
  Teardown:  docker rm -f ${CONTAINER} && docker volume rm ${VOLUME}
EOF
