adminUser: admin
adminPassword: admin
service:
  type: ClusterIP
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.observability.svc.cluster.local
      isDefault: true
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: ""
      type: file
      options:
        path: /var/lib/grafana/dashboards/default
    - name: eval
      orgId: 1
      folder: ""
      type: file
      options:
        path: /var/lib/grafana/dashboards/eval
dashboardsConfigMaps:
  default: agw-dashboard
  eval: agw-dashboard-eval
