apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayPolicy
metadata: { name: f5-jwt, namespace: agentgateway-system }
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: real-f5-std
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
      - issuer: https://tokenomix.demo
        audiences: [agentgateway]
        jwks:
          inline: '{"keys": [{"kty": "RSA", "kid": "tokenomix-1", "use": "sig", "alg": "RS256", "n": "pS4hcX3ev3SRmjhechz0agFIDvO_taW1QUhwVBUhb24YUfjTGByG0VXqOGiuJtudKaEqyTp6Kaf16MhPW5Ksg6-U7-f6ExMZPQbUEEMMTBmFksEcbALgcJgnZ2N-UOSeYYNy5iNyhmx9r2dRZZHKgJdXW-65lGeYKnxQEHvVEC1tlTTYDjdN0dX4SkuMdFn1LVDHbm-16xfbLuf3AlqW2QMoP34FgDPy7tFgocAR5-B1Tf0-rL05yP-wdghFBXpOIBltHm8pQuBSgvZpHwWxcWTKSyM8mj9lNEPc9KSufZzwLvjMDPtivydwaaWRet1GYrvgTUNf5M9J-L401zz4CQ", "e": "AQAB"}]}'
---
apiVersion: enterpriseagentgateway.solo.io/v1alpha1
kind: EnterpriseAgentgatewayPolicy
metadata: { name: f5-rbac, namespace: agentgateway-system }
spec:
  targetRefs:
  - group: enterpriseagentgateway.solo.io
    kind: EnterpriseAgentgatewayBackend
    name: real-f5-std
  backend:
    mcp:
      authorization:
        action: Allow
        policy:
          matchExpressions:
          - 'jwt.role == "admin"'
          - 'jwt.role == "team" && !(mcp.tool.name.startsWith("delete_") || mcp.tool.name.startsWith("remove_"))'
          - 'jwt.role == "readonly" && (mcp.tool.name.startsWith("list_") || mcp.tool.name.startsWith("get_") || mcp.tool.name.startsWith("system") || mcp.tool.name == "failover_status" || mcp.tool.name == "config_sync_status")'
