# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  adminAddr: 0.0.0.0:15000
gateways:
  llm:
    port: 4000
llm:
  gateways:
  - llm
  policies:
    cors:
      allowOrigins:
      - '*'
      - http://0.0.0.0:15000
      allowHeaders:
      - '*'
      allowMethods:
      - GET
      - POST
      - OPTIONS
  providers:
  - name: anthropic
    provider: anthropic
    params:
      apiKey: $ANTHROPIC_API_KEY
  - name: xai
    provider: xai
    params:
      apiKey: $XAI_API_KEY
  models:
  - name: anthropic-claude
    visibility: internal
    provider:
      reference: anthropic
    params:
      model: claude-sonnet-4-6
  - name: xai-grok
    visibility: internal
    provider:
      reference: xai
    params:
      model: grok-4.6
  virtualModels:
  - name: claude
    routing:
      conditional:
        targets:
        - model: anthropic-claude
          when: |
            default(request.headers["x-force-after-hours"], "") != "true"
            && timestamp(request.startTime).getHours() >= 12
            && timestamp(request.startTime).getHours() < 23
        - model: xai-grok
          when: 'true'
